[[news]]
date = "2026-05"
content = "One paper accepted by ICML 2026 🎉"

[[news]]
date = "2026-02"
content = "One paper accepted by CVPR 2026 🎉"

[[news]]
date = "2026-01"
content = "Two papers accepted by ICLR 2026 🎉"

[[news]]
date = "2025-10"
content = "One paper accepted by TPAMI 🎉"
