[[news]]
date = "2026-05"
content = "一篇论文被 ICML 2026 接收 🎉"

[[news]]
date = "2026-02"
content = "一篇论文被 CVPR 2026 接收 🎉"

[[news]]
date = "2026-01"
content = "两篇论文被 ICLR 2026 接收 🎉"

[[news]]
date = "2025-10"
content = "一篇论文被 TPAMI 接收 🎉"
